name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Web
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Token, který už máte uložený z minulého projektu
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          # DŮLEŽITÉ: Publikujeme do stejného repozitáře
          publish_dir: ./public

          # Název vaší domény
          cname: www.danielg.cz